### ISSUE TITLE
VIC_RBM.tar.gz file

### ISSUE THREAD

**Issue by jingheng-huang** [jyearsley/RBM_Tutorial#1]
Hi John,

I'm interested in the VIC-RBM.

In the tutorial, "Unpack the compressed file “VIC_RBM.tar.gz” and at the Unix prompt" -- But I can't find this file. Can you send me a link? thanks.

**Comment by jyearsley** [comment]
Try this:
https://www.hydroshare.org/resource/30ba1b9867c5499aae77edd29a1a3c9f/

There is also a link on the first line of the:
1. Download Example Datasets¶
<https://jyearsleyrbm-mk.readthedocs.io/en/latest/Documentation/run_RBM/#1-download-example-datasets>
Download the example data sets, please refer to Documentation/Sample Dataset
<http://www.hydroshare.org/resource/30ba1b9867c5499aae77edd29a1a3c9f>


---------------------------------------------------------------
John Yearsley
Affiliate Professor
UW-Hydro|Computational Hydrology
University of Washington

***@***.***
uw-hydro.github.io/current_member/john_yearsley

**Comment by jingheng-huang** [comment]
Thanks a lot！
